SELECT * FROM tabela_de_produtos;

#Selecione NOME_DO_PRODUTO, PRECO_DE_LISTA
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
#Caso
CASE
	#SE PRECO_DE_LISTA >= 12 ENTÃO diga que o 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    #SE PRECO_DE_LISTA >= 7 E PRECO_DE_LISTA <12, ENTÃO diga que 'PRODUTO EM CONTA'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA <12 THEN 'PRODUTO EM CONTA'
    #SENÃO diga 'PRODUTO BARATO'
    ELSE 'PRODUTO BARATO'
#FIM e chame essa classificação de STATUS_PRECO da tabela_de_produtos
END AS STATUS_PRECO FROM tabela_de_produtos;

SELECT 
    EMBALAGEM, 
    AVG(PRECO_DE_LISTA) AS PRECO_MEDIO,
    CASE 
        WHEN AVG(PRECO_DE_LISTA) >= 12 THEN 'PRODUTO CARO'
        WHEN AVG(PRECO_DE_LISTA) >= 7 AND AVG(PRECO_DE_LISTA) < 12 THEN 'PRODUTO EM CONTA'
        ELSE 'PRODUTO BARATO'
    END AS STATUS_PRECO
FROM tabela_de_produtos 
GROUP BY EMBALAGEM;